# Generated by Django 2.1.5 on 2021-11-26 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo'),
            preserve_default=False,
        ),
    ]
